# Generated by Django 5.2.4 on 2025-07-16 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
