# Generated by Django 5.2.4 on 2025-07-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_content_alter_like_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='type',
            field=models.CharField(choices=[("O'zbekiston", "O'zbekiston"), ('Jahon', 'Jahon'), ('Iqtisodiyot', 'Iqtisodiyot'), ('Sport', 'Sport'), ('Fan-texnika', 'Fan-texnika'), ('Moliya', 'Moliya'), ("Ta'lim", "Ta'lim"), ('Avto', 'Avto')], default='Journal', max_length=50),
        ),
    ]
